# Generated by Django 4.1.4 on 2023-08-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpName', models.CharField(max_length=20)),
                ('EmpMail', models.EmailField(max_length=100)),
                ('EmpPhoneNumber', models.IntegerField()),
            ],
        ),
    ]
