# Generated by Django 4.1.4 on 2023-08-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emp_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='EmpId',
            field=models.CharField(max_length=20),
        ),
    ]
